replicaCount: 2

image:
  repository: 10.96.125.11:5000/hello-app
  tag: "58ed0cc365a95d0054b3049745f4e670e09ef944"
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30090

app:
  message: "Hello from GitOps!"

resources:
  limits:
    cpu: "200m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "64Mi"
