replicaCount: 2

image:
  repository: 10.96.125.11:5000/hello-app
  tag: "06445e0bf16c141ca19ea8c0907275f43fb1ea54"
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30090

app:
  message: "Hello from GitOps!"

resources:
  limits:
    cpu: "200m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "64Mi"
