replicaCount: 2

image:
  repository: 10.96.125.11:5000/hello-app
  tag: "4e37be4a0a4dcd838957566b5471632ffa76022b"
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30090

app:
  message: "Hello from GitOps!"

resources:
  limits:
    cpu: "200m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "64Mi"
